version: '2.1'
services:
  redis-primary:
    image: 'bitnami/redis:5.0'
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'redis_data:/bitnami/redis/data'

  redis-secondary:
    image: 'bitnami/redis:5.0'
    ports:
      - '6380:6379'
    depends_on:
      - redis-primary
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-primary
      - REDIS_MASTER_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes

  postgres:
    container_name: postgres
    restart: always
    image: giosg/postgres:barmanready-stable
    environment:
      ADD_DB: "cacheops"
      POSTGRES_PASSWORD: "kissanpissa"
    ports:
      - '5432:5432'
  
  postgres_fictive_slave:
    container_name: postgres_fictive_slave
    restart: always
    image: giosg/postgres:barmanready-stable
    environment:
      ADD_DB: "cacheops_slave"
      POSTGRES_PASSWORD: "kissanpissa"
    ports:
      - '5433:5432'


volumes:
  redis_data:
    driver: local